#! /bin/sh
# Copyright (C) 2025 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------


email="$1";

# deleting the number of unread emails (<fullcount>NUMBER</fullcount)
email="$(echo $email | sed 's/<fullcount>[0-9]*<\/fullcount>//')";


CONTENT="$(echo $email | awk 'BEGIN { RS = "" ; FS = "</title>" } { for (i = 2; i <= NF-1; i++) print $i }'))"
WIDTH=$(( $(wc -L <<< "$CONTENT") * 13 / 10 ))

ROFI_OPTIONAL_ARGS=()
if ! [[ -z "$rofi_theme" ]]; then
	ROFI_OPTIONAL_ARGS+=( -theme "$rofi_theme" )
fi
if ! [[ -z "$rofi_window_anchor" ]]; then
	ROFI_OPTIONAL_ARGS+=( -theme-str '#window {anchor:'"$rofi_window_anchor"'; width: '"${WIDTH}"'ch;}' )
else
  ROFI_OPTIONAL_ARGS+=( -theme-str '#window { width: '"${WIDTH}"'ch;}' )
fi


rofi  \
    -e "$CONTENT" \
    -m -3 \
    -no-fixed-num-lines \
    "${ROFI_OPTIONAL_ARGS[@]}"
