#! /bin/sh
date=$(date '+%A, %d %B %Y')

CONTENT="$date
$(cal --color=always -y \
            | sed 's/\x1b\[[7;]*m/\<span background="#FFFFFF" color="#262626"\>\<b\>/g' \
            | sed 's/\x1b\[[27;]*m/\<\/b\>\<\/span\>/g' \
            | tail -n +2)"

rofi -e "$CONTENT" -markup -m -3 -theme "omar-message" -theme-str '#window {anchor:southeast; width:70ch;}'