#!/bin/sh
year=$(date '+%Y')
month=$(date '+%m' | sed 's/^0//')
(( month == 12 )) && month=1 && year=$((year + 1)) || month=$((month + 1))
date=$(cal $month $year | sed -n '1s/^  *//;1s/  *$//p')

CONTENT="$date

$(cal $month $year | tail -n +2)"

rofi_optional_args=()
rofi_window_rasi='width:23ch'

if ! [[ -z "$rofi_theme" ]]; then
	rofi_optional_args+=( -theme "$rofi_theme" )
fi
if ! [[ -z "$rofi_window_anchor" ]]; then
    rofi_window_rasi="anchor:$rofi_window_anchor; $rofi_window_rasi"
fi
rofi_optional_args+=( -theme-str "#window {$rofi_window_rasi;}" )

rofi -e "$CONTENT" -markup -m -3 "${rofi_optional_args[@]}"
