#! /bin/sh
year=$(date '+%Y')
month=$(date '+%m' | sed 's/^0//')
(( month == 12 )) && month=1 && year=$((year + 1)) || month=$((month + 1))
date=$(cal $month $year | sed -n '1s/^  *//;1s/  *$//p')

CONTENT="$date

$(cal --color=always $month $year \
    | sed 's/\x1b\[[7;]*m/\<span background="#FFFFFF" color="#262626"\>\<b\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/b\>\<\/span\>/g' \
    | tail -n +2)"

rofi -e "$CONTENT" -theme "omar-message" -m -3 -theme-str '#window {anchor:southeast; width:23ch;}'
