#! /bin/sh
date=$(date '+%A, %d %B %Y')

rofi_optional_args=()
rofi_window_rasi='width:70ch'

if ! [[ -z "$rofi_theme" ]]; then
	rofi_optional_args+=( -theme "$rofi_theme" )
fi
if ! [[ -z "$rofi_window_anchor" ]]; then
    rofi_window_rasi="anchor:$rofi_window_anchor; $rofi_window_rasi"
fi
rofi_optional_args+=( -theme-str "#window {$rofi_window_rasi;}" )


CONTENT="$date
$(cal --color=always -y \
            | sed 's/\x1b\[[7;]*m/\<span background="#FFFFFF" color="#262626"\>\<b\>/g' \
            | sed 's/\x1b\[[27;]*m/\<\/b\>\<\/span\>/g' \
            | tail -n +2)"

rofi -e "$CONTENT" -markup -m -3 "${rofi_optional_args[@]}"
