#!/usr/bin/env bash

################################
# Show core temperature 
################################

case "$BLOCK_BUTTON" in
    1) ( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && setsid ./mouse-left-click ) > /dev/null  ;;
esac

v=$(sensors | sed 's/([^)]*)//' | grep '+[0-9\.]*°C' | sed 's/[^:]*: *+//' | sort -nr | head -1)
echo ${v::-3} "ºC"
echo ${v::-3} "ºC"