#!/usr/bin/env bash

################################
# Show core temperature 
################################

case "$BLOCK_BUTTON" in
    1) ( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && setsid ./mouse-left-click ) > /dev/null  ;;
esac

v=$(cat /sys/bus/platform/devices/coretemp.0/hwmon/hwmon*/temp1_input)
echo ${v::-3} "ºC"
echo ${v::-3} "ºC"