#!/bin/sh
#
# Copyright 2021 Omar Castro <omar.castro.360@gmail.com>
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi" and shows the battery
# Should work with any POSIX compatible shell

BATTERY="${BLOCK_INSTANCE:-0}"
IFS=, read state percent rem <<INPUT
$(acpi -b | grep "Battery $BATTERY" | sed -r -e 's/%//' -e 's/[^:]+: +//' -e 's/, +/,/g')
INPUT
status=$(case ${state} in
	Full) echo "FULL";;
	Discharging) echo "DIS";;
	Charging) echo "CHR";;
	*) acpi -a | sed -e 's/.*: on-line/CHR/' -e 's/.*: off-line/DIS/';;
esac)
remaining=""

if [ ! -z "${rem}" ]; then
  remaining=" ($(echo ${rem} | cut -f1,2 -d':'))"
fi
echo $percent% $status$remaining
echo $percent% $status

if [ "$status" = "DIS" ]; then
	if [ $percent -le 20 ]; then
		echo "#FF0000";
	elif [ $percent -le 40 ]; then
		echo "#FFAE00";
	elif [ $percent -le 60 ]; then
		echo "#FFF600";
	elif [ $percent -le 85 ]; then
		echo "#A8FF00";
	fi
	if [ $percent -le 5 ]; then
		exit 33
	fi
fi
