#!/bin/sh
#
# Copyright 2021 Omar Castro <omar.castro.360@gmail.com>
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi" and shows the battery
# Should work with any POSIX compatible shell

if [ -z "${BLOCK_INSTANCE}" ]; then
	for x in /sys/class/power_supply/*; do
		if [ "Battery" = "$(cat $x/type)" ] ;then
			BATTERY="$(basename $x)"
			break
		fi
	done
	if [ -z "${BATTERY}" ]; then
		# no battery found, so do not show blocklet
		exit 1
	fi
else
	BATTERY="${BLOCK_INSTANCE}"
fi

percent=$(cat /sys/class/power_supply/$BATTERY/capacity)
state=$(cat /sys/class/power_supply/$BATTERY/status)

status=$(case ${state} in
	Full) echo "FULL";;
	'Not charging') echo "NCHR";;
	Discharging) echo "DIS";;
	Charging) echo "CHR";;
	*) echo "";;
esac)
remaining=""
if [ ! -z "${rem}" ]; then
  remaining=" ($(echo ${rem} | cut -f1,2 -d':'))"
fi
echo $percent% $status$remaining
echo $percent% $status

if [ "$status" = "DIS" ]; then
	if [ $percent -le 20 ]; then
		echo "#FF0000";
	elif [ $percent -le 40 ]; then
		echo "#FFAE00";
	elif [ $percent -le 60 ]; then
		echo "#FFF600";
	elif [ $percent -le 85 ]; then
		echo "#A8FF00";
	fi
	if [ $percent -le 5 ]; then
		exit 33
	fi
fi
