#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${1:-10}" # color will turn red under this value (default: 10%)


case $BLOCK_BUTTON in
    1)
CONTENT=$(df -h | awk '{print $6 " " $4 " / " $2 " " $5}' | tail -n +2 | column -t -N filesystem,free,/,total,use% )
let "WIDTH = $(wc -L <<< "$CONTENT") + 4"
echo "$CONTENT" | tail +2 | awk '/ 9[0-9]%/{print "<span background=\"#ee4835\" foreground=\"#eee8d5\">"$0"</span>"}1' | rofi \
    -dmenu \
    -mesg "$(echo "$CONTENT" | head -n 1 | sed -r 's|([^ ]+)|<b><u>\1</u></b>|g')" \
    -markup \
    -theme "omar-message" \
    -m -3 \
    -theme-str '#window {anchor:southeast; width:'"$WIDTH"'ch;}' \
    -eh 1 \
    -no-fixed-num-lines \
    > /dev/null
	;;

esac

df -h -P -l "$DIR" | awk -v alert_low=$ALERT_LOW '
/\/.*/ {
	# full text
	print $4 "/" $2

	# short text
	print $4

	use=$5

	# no need to continue parsing
	exit 0
}

END {
	gsub(/%$/,"",use)
	if (100 - use < alert_low) {
		# color
		print "#FF5555"
	}
}
'
