#!/bin/bash
# Copyright (C) 2022 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# Use the provided interface, otherwise the device used for the default route.
if [[ -n $BLOCK_INSTANCE ]]; then
  IF=$BLOCK_INSTANCE
else
  IF=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------
case $BLOCK_BUTTON in
  1)

CONTENT=$( ip a \
      | sed ':a;N;$!ba;s/\n  */;/g' \
      | grep inet \
      | sed -r -e "s|^[0-9]+: ([^:]+).*;inet ([^/]+).*;inet6 ([^/]+).*|\1;\2;\3|" -e "s|^[0-9]+: ([^:]+).*;inet6 ([^/]+).*|\1;;\2|" -e "s|^[0-9]+: ([^:]+).*;inet ([^/]+).*|\1;\2;|" \
      | column -s ';' -t -R iface -N 'iface,IPv4,IPv6' \
)
let "WIDTH = $(wc -L <<< "$CONTENT") + 4"
echo "$CONTENT" | tail +2 | rofi \
      -dmenu \
      -mesg "$(echo "$CONTENT" | head -n 1 |  sed -r '1s|([^ ]+)|<b><u>\1</u></b>|g')" \
      -theme "omar-message" \
      -m -3 \
      -theme-str '#window {anchor:southeast;}' \
      -width -$WIDTH \
      -no-fixed-num-lines \
      > /dev/null
esac


if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo down # full text
  echo down # short text
  exit
fi

case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

# if no interface is found, use the first device with a global scope
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")


case $BLOCK_BUTTON in
  3) 
    echo -n "$IPADDR" | xsel -b > /dev/null && rofi -e "copied to clipboard" -m -3 -width -21 -theme-str '#window {anchor:southeast;}' > /dev/null ;;
esac

#------------------------------------------------------------------------

echo "$IPADDR" # full text
echo "$IPADDR" # short text
