#!/usr/bin/env bash
#
# Copyright 2022 Omar Castro <omar.castro.360@gmail.com>
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script calculates the CPU usage without requiring any external depenedency, like mpstat
# it reads directly from /proc/stat and makes he necessary calculations
# Show information of each CPU core on mouse left button click, by using rofi.

unset LANG
LC_ALL=C

usageCPU=$(paste -d " " <(sleep 0.2; grep -P "cpu" /proc/stat) <(grep -P "cpu" /proc/stat) | awk '{ 
  prevIdle=($16 + $17) ;
  idle=($5 + $6) ;
  prevNonIdle=($13 + $14 + $15 + $18 + $19 + $20) ;
  nonIdle=($2 + $3 + $4 + $7 + $8 + $9) ;
  prevTotal=( prevIdle + prevNonIdle );
  total=( idle + nonIdle ) ;
  totald=(total - prevTotal) ;
  idled=(idle - prevIdle) ;
  print $1 " " ((totald - idled)/totald*100) 
}')
totalCpuUsage=$(echo $usageCPU | cut -d" " -f 2 )
usageToShow=$(printf "%.1f%%\n" $totalCpuUsage )

case "$BLOCK_BUTTON" in
    1) ( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null 2>&1 && setsid ./mouse-left-click "$usageCPU" ) > /dev/null  ;;
esac

echo $usageToShow
echo $usageToShow
totalCpuUsageInt=${totalCpuUsage%.*}
if (( $totalCpuUsageInt >= 70 )); then
    echo "#f0c674"
    echo "#dc322f"
elif (( $totalCpuUsageInt >= 50 )); then
    echo "#FFFFFF"
    echo "#666600"
fi